# CodeRabbit 設定ファイル (Python向け)
# ファイル名: .coderabbit.yaml
# 配置場所: リポジトリのルートディレクトリ

# =====================================
# 基本設定
# =====================================

# レビューの言語設定(日本語)
language: "ja"

# 早期アクセス機能を使うかどうか(新機能をいち早く試せる)
early_access: false

# 無料プランを有効にする
enable_free_tier: true

# =====================================
# レビュー設定
# =====================================
reviews:
  # レビューのスタイル設定
  # - "chill": 優しめのレビュー(初心者向け)
  # - "assertive": しっかりめのレビュー
  profile: "chill"

  # 変更をリクエストするワークフローを使うか
  # true にすると、問題があるときに「変更が必要」とマークされる
  request_changes_workflow: false

  # PRの全体的なサマリーを表示するか
  high_level_summary: true

  # レビューに詩を含めるか(ユニークな機能!)
  # true にすると、コード変更を祝う短い詩が追加される
  poem: true

  # レビューステータスを表示するか
  review_status: true

  # ウォークスルー(変更点の説明)を折りたたむか
  collapse_walkthrough: true

  # 自動レビューの設定
  auto_review:
    # 自動レビューを有効にするか
    enabled: true
    
    # ドラフトPRもレビューするか
    # false にすると、ドラフト状態のPRはレビューされない
    drafts: false

  # 特定のファイルパスを無視する設定
  path_filters:
    - "!**/__pycache__/**"  # Pythonのキャッシュフォルダを無視
    - "!**/*.pyc"           # コンパイル済みPythonファイルを無視
    - "!**/venv/**"         # 仮想環境フォルダを無視
    - "!**/env/**"          # 仮想環境フォルダを無視
    - "!**/.pytest_cache/**" # pytestキャッシュを無視

  # Pythonファイル向けの特別なレビュー指示
  path_instructions:
    - path: "**/*.py"
      instructions: |
        以下の点に注意してPythonコードをレビューしてください：
        - PEP8スタイルガイドに従っているか
        - 型ヒント(type hints)が適切に使われているか
        - docstringが関数やクラスに適切に記述されているか
        - エラーハンドリングが適切か
        - 変数名や関数名がわかりやすいか
        - セキュリティ上の問題がないか
        - パフォーマンスの改善余地がないか
    
    - path: "**/*.ipynb"
      instructions: |
        Jupyter Notebookとして以下の点をレビューしてください：
        - セルの実行順序が論理的で理解しやすいか
        - マークダウンセルで十分な説明やコメントがあるか
        - コードセルが長すぎず、適切に分割されているか
        - 変数名やデータフレーム名がわかりやすいか
        - データの可視化（グラフなど）が適切か
        - 不要な出力結果が残っていないか
        - インポート文がノートブックの冒頭にまとまっているか
        - 再現性があるか（乱数シードの設定など）
        - メモリ効率的なコードになっているか
        - エラーハンドリングが適切か
    
    - path: "**/tests/**/*.py"
      instructions: |
        テストコードとして以下を確認してください：
        - テストケースが十分にカバーされているか
        - テスト名がわかりやすいか
        - アサーションが適切か
        - モックやフィクスチャが適切に使われているか

# =====================================
# チャット設定
# =====================================
chat:
  # CodeRabbitからの質問に自動返信するか
  auto_reply: true

# =====================================
# 学習機能設定
# =====================================
knowledge_base:
  # 過去のレビューから学習するか
  learnings:
    scope: repository
  
  # GitHubのissuesから学習するか
  issues:
    scope: auto
  
  # Jiraとの連携(使わない場合は空のまま)
  jira:
    project_keys: []
  
  # Linearとの連携(使わない場合は空のまま)
  linear:
    team_keys: []

# =====================================
# カスタムトーン設定(オプション)
# =====================================
# レビューコメントの口調をカスタマイズできる
# 例: "丁寧な言葉遣いで、建設的なフィードバックをお願いします"
tone_instructions: "簡潔に返答が欲しいが、複数の選択肢がある場合は提示して下さい。"

# =====================================
# 補足説明
# =====================================
# このファイルを使うには:
# 1. リポジトリのルートに .coderabbit.yaml として保存
# 2. GitHubリポジトリにCodeRabbitアプリをインストール
# 3. PRを作成すると自動的にレビューが始まる
#
# 詳細なドキュメント:
# https://docs.coderabbit.ai/